### PR TITLE
Document the files in the revision quickstart

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling would you please throw an eye on this and eventually merge?

**Comment by jpkrohling** [comment]
LGTM. I'd replace "ATM" by "At the moment" or any other wording, but that's a matter of taste :)

**Comment by ppalaga** [comment]
In edc5cb1 I have replaced a couple of ATMs with "at the moment" :)

**Comment by jpkrohling** [comment]
Looks even better now :)

**Pull request merged**
