### PR TITLE
Figure out why we need .mvn/extensions.xml while takari-local-repo does not

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@ifedorenko do you have any idea why our integration tests do not work without `.mvn/extensions.xml` file (that the present pull request removes just to demo the effect)? 

I did my best to do everything here as you did in `takari-local-repository`. But without `.mvn/extensions.xml`, I simply cannot see my local repo implementation being loaded. There is only `[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0...` there in `log.txt`, while I expect `[DEBUG] Using manager SrcdepsLocalRepositoryManager...`

OTOH, when I run your `takari-local-repository` I can see in `log.txt` that your repo impl is being loaded even without `.mvn/extensions.xml` : `[DEBUG] Using manager TakariLocalRepositoryManager with priority 20.0...`

Can you maybe see something important I have forgotten?

**Comment by ppalaga** [comment]
While I am still curious why we need `.mvn/extensions.xml` and `takari-local-repository` does not, this is not that hot anymore because in https://github.com/l2x6/srcdeps/pull/44 , we started exposing our test projects as quickstarts, where it is quite desirable to show the `.mvn/extensions.xml` to the users. Thus closing, but I'd still be thankful for any hints why it did not work here.

**Comment by ifedorenko** [comment]
`MavenRuntimeBuilder#withExtension` adds specified classes directory as Maven core extension, it does not add any dependencies (it operates on files, and does not have access to dependency information). I am guessing that srcdeps-maven-local-repository has required runtime dependencies and fails to load because they are missing. takari-local-repository does not have any required runtime dependencies, so target/classes is sufficient to make tests run.

`.mvn/extensions.xml` is defined in terms of artifacts, at runtime maven will use the artifact and its dependencies.

Hope this makes sense.

**Comment by ppalaga** [comment]
@ifedorenko yes, makes sense. Thanks a lot!

**Pull request closed without merging**
