### PR TITLE
Fix #5 Add a way to depend on tags and eventually also branches

### LINKED ISSUE #5: Add a way to depend on tags and eventually also branches
The rough idea is to change the format of the version string. ATM, we have

```
{whatever-version-string}-SRC-{commitId}
```

After the change, we could have

```
{whatever-version-string}-SRC-{revision|tag|branch}-{revisionId|tagName|branchName}
```

where `revision|tag|branch` are whatever strings acceptable for `scmVersionType` configuration property of SCM plugin https://maven.apache.org/scm/maven-scm-plugin/checkout-mojo.html#scmVersionType
and `revisionId|tagName|branchName` is whatever identifier of the given versionType that will be used as a value for the `scmVersion` property of the SCM plugin https://maven.apache.org/scm/maven-scm-plugin/checkout-mojo.html#scmVersion

Examples after the change:

```
{whatever-version-string}-SRC-{revision|tag|branch}-{revisionId|tagName|branchName}
```

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

**Comment by ppalaga** [comment]
I understand your proposal as an attempt to achieve a simpler configuration, which is a thing worth pursuing, but I see no way to implement it without writing error-prone SCM-specific code.

ATM, the only assumption about the the triple [`scmURL`, `scmVersion` and `scmVersionType`] the srcdeps plugin is making is that the SCM plugin [1] will know how to use those three together. srcdeps plugin makes no claims to know what the possible values of `scmVersionType` are, because they depend on the kind of SCM, which is given by the URL.

The advantage of this approach is first that srcdeps plugin will work for any SCM that the SCM plugin supports. Second, using SCM plugin as a black box [1], we can avoid writing any SCM-specific logic.

I see no elegant way to both adopt your proposal and keep these two advantages.

Other than that, I find such fallbacks quite dangerous because tags and branches can have the same names (in git at least). Omitting an explicit `scmVersionType` from our config and trying `tag` and `branch` in some specific order could lead to checking out the kind of version that user does not want.

[1] https://github.com/ppalaga/srcdeps-maven-plugin/blob/4ad0cd24efbda13e92a921df6e77eb6c0c4ef485/srcdeps-maven-plugin/src/main/java/org/l2x6/maven/srcdeps/SrcdepsInstaller.java#L86-L91

**Comment by jpkrohling** [comment]
Got it, and it makes sense. So, if I try the plugin with Mercurial, should it work?

**Comment by ppalaga** [comment]
> So, if I try the plugin with Mercurial, should it work?

Yes, that is my unproven expectation :)

**Comment by ppalaga** [comment]
> So, if I try the plugin with Mercurial, should it work?

2c6f7c9 is making this a proven fact :)

**Pull request merged**
